import { ModuleData } from '../types';

/**
 * Generates HTML for the Card module
 *
 * NOTE: The card container wrapper is now generated by the compositer
 * to allow content modules to be rendered inside it.
 * This function returns empty as the HTML structure is handled at composition level.
 */
export function getCardHtml(data: ModuleData): string {
  // Card HTML is generated by the compositer to wrap content modules
  // See compositer.ts -> collectHTML() -> generateCardWrapperOpen/Close
  return '';
}
