import { z } from 'zod';

// Styled chunk schema
const styledChunkSchema = z.object({
  text: z.string(),
  color: z.string().optional(),
  fontFamily: z.string().optional(),
  fontSize: z.string().optional(),
  bold: z.boolean().optional(),
  italic: z.boolean().optional(),
  letterSpacing: z.string().optional(),
  backgroundColor: z.string().optional(),
  padding: z.string().optional(),
});

// Card gradient overlay schema
const cardGradientOverlaySchema = z.object({
  enabled: z.boolean().optional(),
  color: z.string().optional(),
  startOpacity: z.number().optional(),
  midOpacity: z.number().optional(),
  height: z.number().optional(),
  direction: z.enum(['to top', 'to bottom', 'to right', 'to left']).optional(),
}).optional();

// Text style schema
const textStyleSchema = z.object({
  fontFamily: z.string().optional(),
  fontSize: z.string().optional(),
  fontWeight: z.string().optional(),
  color: z.string().optional(),
  backgroundColor: z.string().optional(),
  textAlign: z.enum(['left', 'center', 'right']).optional(),
  lineHeight: z.string().optional(),
  letterSpacing: z.string().optional(),
  textTransform: z.enum(['none', 'uppercase', 'lowercase', 'capitalize']).optional(),
  textShadow: z.string().optional(),
  background: z.string().optional(),
  WebkitBackgroundClip: z.string().optional(),
  WebkitTextFillColor: z.string().optional(),
});

// Stack template schema
export const stackTemplateSchema = z.object({
  template: z.string(),
  backgroundColor: z.string().optional(),
  viewportBackgroundType: z.enum(['color', 'image']).default('color'),
  viewportBackgroundColor: z.string().optional(),
  viewportBackgroundImage: z.string().optional(),
  useCard: z.boolean().default(true),
  cardWidth: z.number(),
  cardHeight: z.number(),
  cardBorderRadius: z.number(),
  cardBackgroundType: z.enum(['color', 'image']).default('color'),
  cardBackgroundColor: z.string(),
  cardBackgroundImage: z.string().optional(),
  cardGradientOverlay: cardGradientOverlaySchema,
  reverseLayout: z.boolean().optional(),
  customCardContainerStyles: z.string().optional(),
  customContentImageSectionStyles: z.string().optional(),
  text1: z.string(),
  text2: z.string(),
  text3: z.string(),
  text4: z.string(),
  text5: z.string(),
  text1StyledChunks: z.array(styledChunkSchema).optional(),
  text2StyledChunks: z.array(styledChunkSchema).optional(),
  text3StyledChunks: z.array(styledChunkSchema).optional(),
  text4StyledChunks: z.array(styledChunkSchema).optional(),
  text5StyledChunks: z.array(styledChunkSchema).optional(),
  textGap: z.number(),
  textVerticalAlign: z.enum(['top', 'center', 'bottom']).optional(),
  textPaddingTop: z.number().optional(),
  textPaddingBottom: z.number().optional(),
  textPaddingLeft: z.number().optional(),
  textPaddingRight: z.number().optional(),
  text1Style: textStyleSchema,
  text2Style: textStyleSchema,
  text3Style: textStyleSchema,
  text4Style: textStyleSchema,
  text5Style: textStyleSchema,
  contentImageUrl: z.string().optional(),
  contentImageBorderRadius: z.number().optional(),
  hideContentImage: z.boolean().optional(),
  freeText1: z.string().optional(),
  freeText2: z.string().optional(),
  freeText3: z.string().optional(),
  freeText1Position: z.object({
    top: z.union([z.string(), z.number()]).optional(),
    left: z.union([z.string(), z.number()]).optional(),
    width: z.union([z.string(), z.number()]).optional(),
    height: z.union([z.string(), z.number()]).optional(),
  }).optional(),
  freeText2Position: z.object({
    top: z.union([z.string(), z.number()]).optional(),
    left: z.union([z.string(), z.number()]).optional(),
    width: z.union([z.string(), z.number()]).optional(),
    height: z.union([z.string(), z.number()]).optional(),
  }).optional(),
  freeText3Position: z.object({
    top: z.union([z.string(), z.number()]).optional(),
    left: z.union([z.string(), z.number()]).optional(),
    width: z.union([z.string(), z.number()]).optional(),
    height: z.union([z.string(), z.number()]).optional(),
  }).optional(),
  freeText1Style: textStyleSchema.optional(),
  freeText2Style: textStyleSchema.optional(),
  freeText3Style: textStyleSchema.optional(),
  freeText1SpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  freeText2SpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  freeText3SpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  freeText1SpecialPadding: z.number().optional(),
  freeText2SpecialPadding: z.number().optional(),
  freeText3SpecialPadding: z.number().optional(),
  svg1Content: z.string().optional(),
  svg1Url: z.string().optional(),
  svg1Position: z.object({
    top: z.union([z.string(), z.number()]).optional(),
    left: z.union([z.string(), z.number()]).optional(),
    width: z.union([z.string(), z.number()]).optional(),
    height: z.union([z.string(), z.number()]).optional(),
  }).optional(),
  svg1Color: z.string().optional(),
  svg1SpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  svg1SpecialPadding: z.number().optional(),
  // Arrow fields
  arrowImageUrl: z.string().optional(),
  arrowColor: z.string().optional(),
  arrowImagePosition: z.object({
    top: z.union([z.string(), z.number()]).optional(),
    left: z.union([z.string(), z.number()]).optional(),
    width: z.union([z.string(), z.number()]).optional(),
    height: z.union([z.string(), z.number()]).optional(),
  }).optional(),
  arrowImageSpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  arrowImageSpecialPadding: z.number().optional(),
  arrowContentGap: z.number().optional(),
  // Bottom text (attached to arrow)
  bottomText: z.string().optional(),
  bottomTextStyle: textStyleSchema.optional(),
  bottomTextGapFromArrow: z.number().optional(),
  bottomTextPaddingRight: z.number().optional(),
  bottomTextSpecialPosition: z.enum(['none', 'top-left', 'top-right', 'bottom-left', 'bottom-right']).optional(),
  bottomTextSpecialPadding: z.number().optional(),
});

export type StackTemplateFormData = z.infer<typeof stackTemplateSchema>;

// Default values
export const stackTemplateDefaults: StackTemplateFormData = {
  template: 'stack',
  backgroundColor: '#FF5722',
  viewportBackgroundType: 'color',
  useCard: true,
  cardWidth: 90,
  cardHeight: 90,
  cardBorderRadius: 20,
  cardBackgroundType: 'color',
  cardBackgroundColor: '#ffffff',
  reverseLayout: false,
  text1: '',
  text2: '',
  text3: '',
  text4: '',
  text5: '',
  textGap: 10,
  textVerticalAlign: 'bottom',
  textPaddingTop: 0,
  textPaddingBottom: 0,
  textPaddingLeft: 0,
  textPaddingRight: 0,
  text1Style: {
    fontFamily: 'Arial',
    fontSize: '48px',
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
  },
  text2Style: {
    fontFamily: 'Arial',
    fontSize: '36px',
    fontWeight: 'normal',
    color: '#333333',
    textAlign: 'center',
  },
  text3Style: {
    fontFamily: 'Arial',
    fontSize: '24px',
    fontWeight: 'normal',
    color: '#666666',
    textAlign: 'center',
  },
  text4Style: {
    fontFamily: 'Arial',
    fontSize: '24px',
    fontWeight: 'normal',
    color: '#666666',
    textAlign: 'center',
  },
  text5Style: {
    fontFamily: 'Arial',
    fontSize: '20px',
    fontWeight: 'normal',
    color: '#999999',
    textAlign: 'center',
  },
  freeText1Style: {
    fontFamily: 'Arial',
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#000000',
    backgroundColor: 'transparent',
    textAlign: 'left',
  },
  freeText1SpecialPosition: 'none',
  freeText1SpecialPadding: 8,
  freeText2Style: {
    fontFamily: 'Arial',
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#000000',
    backgroundColor: 'transparent',
    textAlign: 'left',
  },
  freeText2SpecialPosition: 'none',
  freeText2SpecialPadding: 8,
  freeText3Style: {
    fontFamily: 'Arial',
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#000000',
    backgroundColor: 'transparent',
    textAlign: 'left',
  },
  freeText3SpecialPosition: 'none',
  freeText3SpecialPadding: 8,
  svg1Url: '',
  svg1SpecialPosition: 'none',
  svg1SpecialPadding: 8,
  // Arrow defaults
  arrowImageUrl: '',
  arrowColor: '#ffffff',
  arrowImageSpecialPosition: 'bottom-right',
  arrowImageSpecialPadding: 6,
  arrowContentGap: 20,
  bottomText: '',
  bottomTextStyle: {
    fontFamily: 'Arial',
    fontSize: '18px',
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'right',
  },
  bottomTextGapFromArrow: 15,
  bottomTextPaddingRight: 0,
  bottomTextSpecialPosition: 'none',
  bottomTextSpecialPadding: 6,
};
